// <auto-generated />
using System;
using FrameworkRepositoryGenerico.DataBase.Entidades;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FrameworkRepositoryGenerico.WebAPI.Migrations
{
    [DbContext(typeof(MyCadastroContext))]
    [Migration("20190424143739_Initial3")]
    partial class Initial3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("FrameworkRepositoryGenerico.DataBase.Entidades.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Cpf");

                    b.Property<string>("Nome");

                    b.Property<string>("Rg");

                    b.HasKey("Id");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("FrameworkRepositoryGenerico.DataBase.Entidades.Contato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Descricao");

                    b.Property<int?>("TipoContatoId");

                    b.Property<int?>("UsuarioId");

                    b.HasKey("Id");

                    b.HasIndex("TipoContatoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Contato");
                });

            modelBuilder.Entity("FrameworkRepositoryGenerico.DataBase.Entidades.Endereco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Bairro");

                    b.Property<string>("Cep");

                    b.Property<int?>("ClienteId");

                    b.Property<string>("Logradouro");

                    b.Property<string>("Municipio");

                    b.Property<string>("Uf");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("Endereco");
                });

            modelBuilder.Entity("FrameworkRepositoryGenerico.DataBase.Entidades.TipoContato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Descricao");

                    b.HasKey("Id");

                    b.ToTable("TipoContato");
                });

            modelBuilder.Entity("FrameworkRepositoryGenerico.DataBase.Entidades.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("ClienteId");

                    b.Property<string>("Cpf");

                    b.Property<string>("Nome");

                    b.Property<string>("senha");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("FrameworkRepositoryGenerico.DataBase.Entidades.Contato", b =>
                {
                    b.HasOne("FrameworkRepositoryGenerico.DataBase.Entidades.TipoContato", "TipoContato")
                        .WithMany()
                        .HasForeignKey("TipoContatoId");

                    b.HasOne("FrameworkRepositoryGenerico.DataBase.Entidades.Usuario", "Usuario")
                        .WithMany("Contato")
                        .HasForeignKey("UsuarioId");
                });

            modelBuilder.Entity("FrameworkRepositoryGenerico.DataBase.Entidades.Endereco", b =>
                {
                    b.HasOne("FrameworkRepositoryGenerico.DataBase.Entidades.Cliente", "Cliente")
                        .WithMany("Endereco")
                        .HasForeignKey("ClienteId");
                });

            modelBuilder.Entity("FrameworkRepositoryGenerico.DataBase.Entidades.Usuario", b =>
                {
                    b.HasOne("FrameworkRepositoryGenerico.DataBase.Entidades.Cliente", "Cliente")
                        .WithMany("Usuario")
                        .HasForeignKey("ClienteId");
                });
#pragma warning restore 612, 618
        }
    }
}
