// <auto-generated />
using System;
using FrameworkRepositoryGenerico.DataBase.Entidades;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FrameworkRepositoryGenerico.WebAPI.Migrations
{
    [DbContext(typeof(MyCadastroContext))]
    partial class MyCadastroContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("FrameworkRepositoryGenerico.DataBase.Entidades.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Ativo");

                    b.Property<string>("Cpf_Cnpj");

                    b.Property<string>("Nome");

                    b.Property<int?>("TipoClienteId");

                    b.HasKey("Id");

                    b.HasIndex("TipoClienteId");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("FrameworkRepositoryGenerico.DataBase.Entidades.Contato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Ativo");

                    b.Property<string>("Descricao");

                    b.Property<int?>("TipoContatoId");

                    b.Property<int?>("UsuarioId");

                    b.HasKey("Id");

                    b.HasIndex("TipoContatoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Contato");
                });

            modelBuilder.Entity("FrameworkRepositoryGenerico.DataBase.Entidades.Endereco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Ativo");

                    b.Property<string>("Bairro");

                    b.Property<string>("Cep");

                    b.Property<int?>("ClienteId");

                    b.Property<string>("Logradouro");

                    b.Property<string>("Municipio");

                    b.Property<string>("Uf");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("Endereco");
                });

            modelBuilder.Entity("FrameworkRepositoryGenerico.DataBase.Entidades.Regra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Ativo");

                    b.Property<string>("Descricao");

                    b.HasKey("Id");

                    b.ToTable("Regra");
                });

            modelBuilder.Entity("FrameworkRepositoryGenerico.DataBase.Entidades.TipoCliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Ativo");

                    b.Property<string>("Descricao");

                    b.HasKey("Id");

                    b.ToTable("TipoCliente");
                });

            modelBuilder.Entity("FrameworkRepositoryGenerico.DataBase.Entidades.TipoContato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Ativo");

                    b.Property<string>("Descricao");

                    b.HasKey("Id");

                    b.ToTable("TipoContato");
                });

            modelBuilder.Entity("FrameworkRepositoryGenerico.DataBase.Entidades.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Ativo");

                    b.Property<int?>("ClienteId");

                    b.Property<string>("Cpf");

                    b.Property<string>("Nome");

                    b.Property<string>("Senha");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("FrameworkRepositoryGenerico.DataBase.Entidades.UsuarioRegra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("RegraId");

                    b.Property<int?>("UsuarioId");

                    b.HasKey("Id");

                    b.HasIndex("RegraId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("UsuarioRegra");
                });

            modelBuilder.Entity("FrameworkRepositoryGenerico.DataBase.Entidades.Cliente", b =>
                {
                    b.HasOne("FrameworkRepositoryGenerico.DataBase.Entidades.TipoCliente", "TipoCliente")
                        .WithMany()
                        .HasForeignKey("TipoClienteId");
                });

            modelBuilder.Entity("FrameworkRepositoryGenerico.DataBase.Entidades.Contato", b =>
                {
                    b.HasOne("FrameworkRepositoryGenerico.DataBase.Entidades.TipoContato", "TipoContato")
                        .WithMany()
                        .HasForeignKey("TipoContatoId");

                    b.HasOne("FrameworkRepositoryGenerico.DataBase.Entidades.Usuario", "Usuario")
                        .WithMany("Contatos")
                        .HasForeignKey("UsuarioId");
                });

            modelBuilder.Entity("FrameworkRepositoryGenerico.DataBase.Entidades.Endereco", b =>
                {
                    b.HasOne("FrameworkRepositoryGenerico.DataBase.Entidades.Cliente", "Cliente")
                        .WithMany("Enderecos")
                        .HasForeignKey("ClienteId");
                });

            modelBuilder.Entity("FrameworkRepositoryGenerico.DataBase.Entidades.Usuario", b =>
                {
                    b.HasOne("FrameworkRepositoryGenerico.DataBase.Entidades.Cliente", "Cliente")
                        .WithMany("Usuarios")
                        .HasForeignKey("ClienteId");
                });

            modelBuilder.Entity("FrameworkRepositoryGenerico.DataBase.Entidades.UsuarioRegra", b =>
                {
                    b.HasOne("FrameworkRepositoryGenerico.DataBase.Entidades.Regra", "Regra")
                        .WithMany("UsuarioRegras")
                        .HasForeignKey("RegraId");

                    b.HasOne("FrameworkRepositoryGenerico.DataBase.Entidades.Usuario", "Usuario")
                        .WithMany("UsuarioRegras")
                        .HasForeignKey("UsuarioId");
                });
#pragma warning restore 612, 618
        }
    }
}
